### PR TITLE
Outlier classification

### PR DESCRIPTION
**Pull request by erwald**
So we have this issue with the data:

screenshot 2019-01-21 at 23 07 34

Namely, there are a lot of outliers at ~-30. As an experiment, I tried manually removing those from the training set, and lo! the model suddenly performed far better.

So I thought, as another experiment, I would build a classifier model which either marks a `card_id` as an outlier or not. If it's an outlier, we could then give it the value that we know all outliers have; if not, we would run it through our regressor as we have done with all samples so far.

Unfortunately the classifier is not able to distinguish well between outliers and non-outliers (for now). But maybe we can revisit the idea when we have done more feature engineering.

As a bonus, there are also some improvements to the main notebook, `elo_loyalty_prediction.ipynb`.

### CODE REVIEW

**Comment by erwald** [comment]
The fact that we are to use root mean squared error as the final metric makes it so that the outliers have a Brobdingnagian impact on the overall error. Quoth Wikipedia:

> RMSD is the square root of the average of squared errors. The effect of each error on RMSD is proportional to the size of the squared error; thus larger errors have a disproportionately large effect on RMSD. Consequently, RMSD is sensitive to outliers.

**Comment by boris-tschirschwitz** [comment]
Do you also get these warnings for some of the cells?

/Users/borist/Projects/Python/kaggle-competition-elo-loyalty-prediction/env/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Users/borist/Projects/Python/kaggle-competition-elo-loyalty-prediction/env/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

**Comment by boris-tschirschwitz** [comment]
I like the idea of training a learner to find the outliers very much. Let's hope we find a way to use it.

**Comment by erwald** [comment]
> Do you also get these warnings for some of the cells? [...]

Yep – I was simply ignoring them. 😅

**Pull request merged**
