### PR TITLE
Bayesian hyperparameter optimizing

### PR DESCRIPTION
**Pull request by erwald**
Running `make processdata` now takes something like another 2 hours, but the good news is that, after you've done that, you never need to do it again, and can with a simple

```py
train_and_validation_df = pd.read_csv('data/processed/train_with_aggregated_features.csv', index_col='card_id')
test_df = pd.read_csv('data/processed/test_with_aggregated_features.csv', index_col='card_id')
```

load the processed / engineered data into any notebook and feed it into whichever model you like.

The best I got on our validation set (please try to do the same train/validation split as in the main notebook if you do some experiments) so far is 3.8674747861251113, but I think that can be improved further by tuning the hyperparameters.

I also implemented a Bayesian hyperparameter optimizer, producing some nice (hmm, hmm) graphs like this:

screenshot 2019-02-05 at 17 35 52
screenshot 2019-02-05 at 17 35 47

Training a model is quite slow though, and I think we probably want to give it 100 or more tries before it finds an optimal set of hyperparameters, which, I think, would take days to compute. It's possible to make it run them in parallel, which should speed things up _a lot_, but that requires setting up some mongodb instance which wasn't what I felt like doing at the moment. ;-)

### CODE REVIEW

**Comment by boris-tschirschwitz** [comment]
@erwald 
Have you seen
`TypeError: diff() got an unexpected keyword argument 'axis'`
before when in
`source activate && python clean_transactions.py --calculate_time_since_purchase_with_merchant data/unzipped/historical_transactions.csv data/processed/historical_transactions.csv
Computing and adding `elapsed_since_last_purchase` column ...
Computing and adding `elapsed_since_last_merch_purchase` column.
This takes a hell of a long time ...
`
?

**Comment by erwald** [comment]
No, I have not. Could it be that you have an older version of pandas installed?

**Comment by boris-tschirschwitz** [comment]
I think I got this because my default python3 was only 3.6, not 3.7.

**Comment by boris-tschirschwitz** [comment]
Looks like it's not just v3.7. Weirdly, I only get the error with the second set. I'll try without
`--calculate_time_since_purchase_with_merchant`.

**Comment by boris-tschirschwitz** [comment]
Apparently the default for `calculate_time_since_purchase_with_merchant` is `true` :-)

**Comment by erwald** [comment]
Oops, that is a mistake for sure! For me it worked but gave a column of `NaN`s for the run on the new_merchant_transactions data. But it still ran without errors. Weird!

**Comment by boris-tschirschwitz** [comment]
It definitely happens in `add_time_since_last_purchase_with_merchant` for historical_transactions.

**Review by boris-tschirschwitz — APPROVED** [review]

**Comment by boris-tschirschwitz** [comment]
Yay, it's now also compiling on my computer.

**Pull request merged**
